name: smart_tools_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  torch_light: ^1.0.2
  flutter_compass: ^0.8.0
  geolocator: ^10.1.0
  noise_meter: ^5.0.0
  record: ^6.1.2
  audioplayers: ^5.2.0
  permission_handler: ^11.1.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  vector_math: ^2.1.4
  sensors_plus: ^5.0.0
  light: ^4.1.0
  device_info_plus: ^10.0.0
  mobile_scanner: ^5.0.0
  math_expressions: ^3.1.0
  battery_plus: ^6.0.0
  connectivity_plus: ^6.0.0
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
